### ISSUE TITLE
Non sound in fedora 32

### ISSUE THREAD

**Issue by slyholborn** [manucontrovento/SpinTool#27]
Hi! Everything works well (way better than in superboucle) on my fedora 32, exept that i have no sound (got some on super boucle) Here's what the console is saying : 
`Initialize settings
Settings initialized
Initialize common
Common initialized
QSocketNotifier: Can only be used with threads started with QThread
inotify_add_watch(/home/sylvain/.config/ibus/bus/b91dffc67463443d9745304768730285-unix-0) failed: (No space left on device)
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
From cffi callback <function Client.set_process_callback.<locals>.callback_wrapper at 0x7f928d254af0>:
Traceback (most recent call last):
  File "/home/sylvain/Téléchargements/Softs/SpinTool-2020-08-23/superboucle/jack.py", line 878, in callback_wrapper
    return callback(frames)
  File "superboucle/spin.py", line 295, in my_callback
    ch_id % song.channels(clip),
  File "/home/sylvain/Téléchargements/Softs/SpinTool-2020-08-23/superboucle/clip.py", line 245, in channels
    return self.data[clip.audio_file].shape[1]
IndexError: tuple index out of range
`
Nothing about jack so i'm not sure if the console output is sound related... Any idea? 
Great work by the way! Thanks!

**Comment by manucontrovento** [comment]
Hi @slyholborn and thanks for writing. Unfortunately, about audio "engine" I'm not so skilled (e.g. I wanted to apply some changes as well, but I found out that dealing with audio and jack in python is not that simple). So all my improvements are related to other features at the moment.
Anyway, it seems something related to audio file. Could you attach the .sbs song file, so that I can try it on my SpinTool? 
I think we could discover what's the problem, by exclusion.
bye! 
Manu

**Comment by sonejostudios** [comment]
Hi @slyholborn 
 I'm wondering about `(No space left on device)` ... is your memory full?
It looks like the audio data can't be copied to memory, thus while ST tries to read it from memory, the (reading-) "index is out of bound".

**Comment by slyholborn** [comment]
No, memory is good, the monitoring is around 75%. I had the same issue in superboucle once. Can't remember if i had sound at this time... I run a RT kernel and realtim priorities are OK.

**Comment by slyholborn** [comment]
I just noticed that if green stops blinking once I click the window, the progression bar won't move...

**Comment by sonejostudios** [comment]
> I just noticed that if green stops blinking once I click the window, the progression bar won't move...

If the progress bar is not moving, there is no audio data to read in memory.

Is this happening with an old song or is this a new song you just created? Please create a new song with only one clip a look if it works.

If this still not works, it might be a problem with pysoundfile. Which version of pysoundfile do you have on your computer? ST needs the latest (at least >= 0.8.0)

in the terminal, try:
```
python3
import soundfile
soundfile.__version__
```

**Comment by slyholborn** [comment]
[sylvain@juloubureau ~]$ python3
Python 3.8.5 (default, Aug 12 2020, 00:00:00) 
[GCC 10.2.1 20200723 (Red Hat 10.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import soundfile
>>> soundfile.__version__
'0.9.0'
>>>

**Comment by slyholborn** [comment]
it's a test with a solo clip (wav format) which works on superboucle

**Comment by sonejostudios** [comment]
Okay, everything looks fine.

Could you send us this new .sbs song with one clip? I could try on my setup.

**Comment by slyholborn** [comment]
https://drive.google.com/file/d/16kDjojLbY5BQsCdlkt5BksCz1PwC6D-Z/view?usp=sharing

**Comment by sonejostudios** [comment]
Okay, the song is playing on my setup (nice guitar btw!). 
@manucontrovento any idea what it could be?

@slyholborn is this song playing on Superboucle?

**Comment by slyholborn** [comment]
Argh, yesterday it did, but not today... 
```
/SuperBoucle.sh 
QSocketNotifier: Can only be used with threads started with QThread
inotify_add_watch(/home/sylvain/.config/ibus/bus/b91dffc67463443d9745304768730285-unix-0) failed: (No space left on device)
From cffi callback <function Client.set_process_callback.<locals>.callback_wrapper at 0x7f81ec2eaaf0>:
Traceback (most recent call last):
  File "/home/sylvain/Téléchargements/Softs/superboucle-master/superboucle/jack.py", line 878, in callback_wrapper
    return callback(frames)
  File "superboucle/boucle.py", line 111, in my_callback
    buffer[:length] += data
ValueError: non-broadcastable output operand with shape (256,) doesn't match the broadcast shape (256,256)
^CTraceback (most recent call last):
  File "/home/sylvain/Téléchargements/Softs/superboucle-master/superboucle/gui.py", line 638, in toggleBlinkButton
    def toggleBlinkButton(self):

```

**Comment by slyholborn** [comment]
I know it has wayland issues but it should'nt affect sound, should it?

**Comment by sonejostudios** [comment]
Well, it could be a wayland thing.... but unfortunately I have no clue about wayland...

It would be really interesting to know if this songs plays with Souperboucle, because then, we can narrow the bug possibilities.

**Comment by manucontrovento** [comment]
Unfortunately I have no clue about wayland, too... The only idea I had is what @sonejostudios already tried: loading your song
I suggest the same: let's find out if this songs plays with Souperboucle

**Comment by slyholborn** [comment]
it doesn't play in superboucle, neither in a wayland nor in a xorg session...

**Comment by manucontrovento** [comment]
As soon as possible I'll try loading the song too. But I think I'll get the same result as @sonejostudios

**Comment by manucontrovento** [comment]
Unfortunately, I have no clues.. 
I opened the .sbs package and on my system it works... 
Maybe we should check on some fedora+jack related forum?
